# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 01:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('bankName', models.CharField(max_length=50)),
                ('cardNumber', models.CharField(max_length=50)),
                ('cardType', models.CharField(default='D', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PeriodOfValidity', models.DateTimeField()),
                ('balance', models.IntegerField(default=0)),
                ('modifyDate', models.DateTimeField(default=datetime.datetime(2016, 10, 5, 1, 4, 41, 405402, tzinfo=utc))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeClear.Accounts')),
            ],
        ),
    ]
